[package]
name = "discord-webhook-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
minreq = { version = "2.7", features = ["https"] }
rocket = { version = "0.5.1", default-features = false, features = ["json"] }
